name: 'Deploy React'
description: 'Deploy a React application. Intended to be used in conjunction with -build, and -test.'

inputs:
  repository:
    description: 'Github Repo'
    required: true
  app-name:
    description: 'App name.'
    required: true
  target-environment:
    description: 'Environment to deploy to'
    required: true
    default: 'None'
  aws-role-dev:
    description: 'The relevant dev build role for AWS.'
    required: true
  aws-role-prod:
    description: 'The relevant prod build role for AWS.'
    required: true
  aws-access-key-id:
    description: 'AWS access key'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'Regionality of the AWS credentialing'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Build Role
      id: set-role
      uses: source-ip/actions-set-build-role@v1.0.0
      with:
        prod-role: ${{ inputs.aws-role-prod }}
        dev-role: ${{ inputs.aws-role-dev }}
        environment-name: ${{ inputs.target-environment }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ steps.set-role.outputs.build-role }}
        role-duration-seconds: 1200
        role-skip-session-tagging: true
    - name: Get App Config
      uses: source-ip/actions-aws-ssm-get-by-path@v1.0.0
      with:
        paths: ${{ format('/app/{0},/app/{0}/{1}/', inputs.app-name, inputs.target-environment) }}
        save-to-environment: true
        file: .env
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: client
    - name: Upload to S3 with no cach
      shell: bash
      run: aws s3 sync --cache-control 'no-cache' . "s3://${APP_BUCKET}"
    - name: Invalidate Cloudfront
      shell: bash
      run: aws cloudfront create-invalidation --distribution-id ${APP_CLOUDFRONT_ID} --paths "/*"